### ISSUE TITLE
Error [ERR_HTTP2_INVALID_SESSION]

### ISSUE THREAD

**Issue by victorHugoCarvalho** [eladnava/fcm-v1-http2#7]
I am getting the following error, but even placing the cache the error is not captured.

Error [ERR_HTTP2_INVALID_SESSION]: The session has been destroyed.
at FCM.sendRequest(/layers/google.ndejs.yarn/yarn_modules/node_modules/fcm-v1-http2/dist/fcm.js:135)

**Comment by eladnava** [comment]
Hi @victorHugoCarvalho,
Thanks for reporting this issue.

This error has now been resolved in commit 85d48ee and in version `1.0.7` of the package via implementation of a retry HTTP/2 client instance in case the original instance gets destroyed.

Please update to the latest version by running:

```
npm install fcm-v1-http2@latest --save
```

Please let me know if you face any issues.

**Comment by victorHugoCarvalho** [comment]
Hi @eladnava, 

I updated the lib here, but the problem still appears.

Could the problem be the number of batches? Because I'm passing batches of 100, the way you implemented it, what is the limit of tokens we can pass?

**Comment by eladnava** [comment]
Hi @victorHugoCarvalho,
That's curious, since there is a check for `client.destroyed` in which case the `retryClient` gets used instead, so not sure how you're still running into `ERR_HTTP2_INVALID_SESSION` after updating.

The library supports an infinite amount of tokens, so there is no limit. But you should not be batching them - the library takes care of batching automatically. You should simply be sending the array of tokens as-is:

```
const tokens = ['ccw_syAXSNOY9ml-Kqh9wo:APA91bHAEQccW1ZpbPvsGc0LFyjEthAt_GZO7HkBGiKounM................uIDEHijb4UR5f3dhyjhO5IbiWhJAA7RVp63KSFCg384PR7nfKADReWUONEJlCnHo15WwZagVTmFcgW'];

// Set FCM API v1 message params
const message = {
    data: {
        // Set custom payload
        message: 'Hello World'
    }
};

// Send the notification
client.sendMulticast(message, tokens);
```

Since FCM imposes a limit of 100 concurrent requests per connection, the library splits the `tokens` array you provide into groups of 100, and then sends the batches equally over the default limit of 10 concurrent HTTP/2 connections.

How many tokens are you trying to send to simultaneously? Have you tried increasing the `maxConcurrentConnections` passed into `fcmV1Http2()`?

Also, please ensure your server / instance has enough CPU / outgoing network bandwidth to support the amount of notifications you're trying to send out simultaneously.
